# Generated by Django 6.0.2 on 2026-02-14 02:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Service name", max_length=100, unique=True
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("product", "Product Service"),
                            ("user", "User Service"),
                            ("order", "Order Service"),
                            ("payment", "Payment Service"),
                            ("inventory", "Inventory Service"),
                            ("frontend", "Frontend Service"),
                        ],
                        help_text="Type of service",
                        max_length=20,
                    ),
                ),
                ("base_url", models.URLField(help_text="Base URL of the service")),
                (
                    "port",
                    models.PositiveIntegerField(default=8000, help_text="Service port"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether the service is active"
                    ),
                ),
                (
                    "health_check_url",
                    models.URLField(
                        blank=True, help_text="Health check endpoint", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(help_text="API path pattern", max_length=255),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="GET",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "requires_auth",
                    models.BooleanField(
                        default=False, help_text="Whether route requires authentication"
                    ),
                ),
                (
                    "rate_limit",
                    models.PositiveIntegerField(
                        default=100, help_text="Requests per minute limit"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Route description"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routes",
                        to="gateway.service",
                    ),
                ),
            ],
            options={
                "ordering": ["path", "method"],
                "unique_together": {("path", "method")},
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(help_text="API key", max_length=255, unique=True),
                ),
                ("name", models.CharField(help_text="Key name/owner", max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Expiration date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, help_text="Last usage timestamp", null=True
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_keys",
                        to="gateway.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("path", models.CharField(max_length=500)),
                ("status_code", models.PositiveIntegerField()),
                (
                    "response_time",
                    models.FloatField(help_text="Response time in milliseconds"),
                ),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "api_key",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gateway.apikey",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gateway.route",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="gateway_req_created_467bd8_idx"
                    ),
                    models.Index(
                        fields=["status_code"], name="gateway_req_status__55c407_idx"
                    ),
                    models.Index(
                        fields=["route"], name="gateway_req_route_i_fa055f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RateLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        help_text="Rate limit identifier (IP, API key, etc.)",
                        max_length=255,
                    ),
                ),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("window_start", models.DateTimeField()),
                ("window_end", models.DateTimeField()),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="gateway.route"
                    ),
                ),
            ],
            options={
                "unique_together": {("identifier", "route", "window_start")},
            },
        ),
    ]
